import Foundation
import FirebaseFirestore
import FirebaseAuth
import Combine

class FirestoreService: ObservableObject {
    static let shared = FirestoreService()
    private let db = Firestore.firestore()
    
    // Published property to be observed by ViewModels if needed directly, 
    // though we might prefer returning publishers.
    @Published var wallets: [Wallet] = []
    
    private var walletsListener: ListenerRegistration?
    private var currentListenerUserId: String? // Track current user
    
    private init() {}
    
    // MARK: - Wallet Operations
    
    /// Create a new wallet
    func createWallet(name: String, type: WalletType, context: WalletContext, performAsUser uid: String) async throws -> Wallet {
        // 1. Check Pro Status and Wallet Limit
        let userDoc = try await db.collection("users").document(uid).getDocument()
        if let user = try? userDoc.data(as: User.self), !user.isPro {
            // Count existing wallets where user is owner
            let snapshot = try await db.collection("wallets")
                .whereField("ownerId", isEqualTo: uid)
                .getDocuments()
            
            if snapshot.documents.count >= 2 {
                throw NSError(domain: "Finvo", code: 403, userInfo: [NSLocalizedDescriptionKey: "Ücretsiz planda en fazla 2 cüzdan oluşturabilirsiniz. Sınırsız cüzdan için Pro'ya yükseltin."])
            }
        }

        let newWalletRef = db.collection("wallets").document()
        
        let wallet = Wallet(
            id: newWalletRef.documentID,
            name: name,
            ownerId: uid,
            type: type,
            context: context,
            members: [uid],
            permissions: [uid: "owner"]
        )
        
        try newWalletRef.setData(from: wallet)
        
        // Optimistic Update
        DispatchQueue.main.async {
            self.wallets.append(wallet)
        }
        
        return wallet
    }
    
    func createWallet(name: String, type: WalletType, context: WalletContext) async throws -> Wallet {
        guard let uid = AuthenticationManager.shared.user?.uid else {
            throw NSError(domain: "Auth", code: 401, userInfo: [NSLocalizedDescriptionKey: "User not logged in"])
        }
        
        let newWallet = Wallet(
            name: name,
            ownerId: uid,
            type: type,
            context: context,
            members: [uid],
            permissions: [uid: "owner"],
            monthlyLimit: 0,
            savingsGoal: 0
        )
        
        // Add to Firestore
        try db.collection("wallets").document(newWallet.id ?? UUID().uuidString).setData(from: newWallet)
        
        // Optimistic Update can be tricky if ID is auto-generated by Firestore? 
        // Here we use UUID().uuidString if nil, but Wallet struct usually has UUID.
        // Actually Wallet struct has `id`? Let's assume it keeps the ID.
        // If we use `addDocument`, Firestore generates ID.
        // Let's use `setData` with the ID from struct.
        
        DispatchQueue.main.async {
            self.wallets.append(newWallet)
        }
        
        return newWallet
    }
    
    /// Listen for wallets where the user is a member
    func startListeningWallets(forUser uid: String) {
        // If already listening for this user, do nothing to prevent flicker
        if walletsListener != nil && currentListenerUserId == uid {
            return
        }
        
        // Remove existing listener if any (for different user)
        stopListeningWallets()
        
        currentListenerUserId = uid
        
        // Query: wallets where 'members' array contains uid
        // Note: 'array-contains' requires an index potentially.
        walletsListener = db.collection("wallets")
            .whereField("members", arrayContains: uid)
            .addSnapshotListener { [weak self] querySnapshot, error in
                guard let self = self else { return }
                
                if let error = error {
                    print("Error listening for wallets: \(error)")
                    return
                }
                
                guard let documents = querySnapshot?.documents else {
                    self.wallets = []
                    return
                }
                
                self.wallets = documents.compactMap { document in
                    try? document.data(as: Wallet.self)
                }
            }
    }
    
    func getWallet(id: String) async throws -> Wallet {
        let doc = try await db.collection("wallets").document(id).getDocument()
        return try doc.data(as: Wallet.self)
    }
    
    func stopListeningWallets() {
        walletsListener?.remove()
        walletsListener = nil
        wallets = []
    }
    
    func updateWallet(_ wallet: Wallet) async throws {
        guard let id = wallet.id else { return }
        try db.collection("wallets").document(id).setData(from: wallet, merge: true)
    }
    
    func deleteWallet(walletId: String) async throws {
        // Optimistic Update: Remove locally first
        DispatchQueue.main.async {
            self.wallets.removeAll { $0.id == walletId }
        }
        
        // 1. Delete transactions (In a real app, use Cloud Functions or batch delete)
        // For MVP, we might leave them orphaned or try to delete a batch.
        // Let's just delete the wallet document for now.
        try await db.collection("wallets").document(walletId).delete()
    }
    
    func leaveWallet(walletId: String, userId: String) async throws {
        // Optimistic Update: Remove locally first
        DispatchQueue.main.async {
            self.wallets.removeAll { $0.id == walletId }
        }
        
        // Remove user from members array and permissions map
        try await removeMember(walletId: walletId, userId: userId)
    }
    
    // MARK: - Transaction Operations
    
    func addTransaction(walletId: String, transaction: Transaction) async throws {
        let walletRef = db.collection("wallets").document(walletId)
        let transactionsRef = walletRef.collection("transactions")
        
        try transactionsRef.addDocument(from: transaction)
    }
    
    // Real-time Transaction Listener
    func listenToTransactions(walletId: String, limit: Int = 50, completion: @escaping ([Transaction]) -> Void) -> ListenerRegistration {
        let walletRef = db.collection("wallets").document(walletId)
        
        // Listen to the last 50 transactions regardless of type
        // This allows client-side filtering without missing data
        let query = walletRef.collection("transactions")
            .order(by: "date", descending: true)
            .limit(to: limit)
            
        return query.addSnapshotListener { snapshot, error in
            guard let documents = snapshot?.documents else {
                print("Error listening to transactions: \(error?.localizedDescription ?? "Unknown error")")
                completion([])
                return
            }
            
            let transactions = documents.compactMap { try? $0.data(as: Transaction.self) }
            completion(transactions)
        }
    }
    
    func deleteTransaction(walletId: String, transactionId: String) async throws {
        let walletRef = db.collection("wallets").document(walletId)
        let transactionRef = walletRef.collection("transactions").document(transactionId)
        try await transactionRef.delete()
    }
    
    func updateTransaction(walletId: String, transaction: Transaction) async throws {
        guard let transactionId = transaction.id else { return }
        let walletRef = db.collection("wallets").document(walletId)
        let transactionRef = walletRef.collection("transactions").document(transactionId)
        
        // 2. Update Transaction
        try transactionRef.setData(from: transaction, merge: true)
        
        // 3. Sync with Linked Debt if applicable
        if let debtId = transaction.linkedDebtId {
             // Fetch Debt
             let debtRef = walletRef.collection("debts").document(debtId)
             var debt = try await debtRef.getDocument(as: Debt.self)
             
             // Check if amount changed
             if transaction.amount != debt.installmentAmount {
                 // User corrected the installment amount.
                 // We should update the Debt definition to match this correction.
                 // Assumption: The user wants to fix the ENTIRE debt plan based on this correction.
                 
                 debt.installmentAmount = transaction.amount
                 debt.totalAmount = Double(debt.totalInstallments) * debt.installmentAmount
                 
                 // Recalculate remaining amount:
                 // Remaining = (Total - PaidCount) * NewInstallment
                 // Note: We assume 'paidInstallments' logic is handled elsewhere (e.g., creating this transaction incremented it).
                 // So remaining is simply the rest.
                 let remainingCount = debt.totalInstallments - debt.paidInstallments
                 debt.remainingAmount = Double(remainingCount) * debt.installmentAmount
                 
                 // Save Debt Update
                 try debtRef.setData(from: debt, merge: true)
             }
        }
    }
    
    // Legacy fetch (kept for reference or specific use cases)
    func fetchTransactions(walletId: String, limit: Int = 20, lastDoc: DocumentSnapshot? = nil, type: TransactionType? = nil) async throws -> (transactions: [Transaction], lastDoc: DocumentSnapshot?) {
        let walletRef = db.collection("wallets").document(walletId)
        var query: Query = walletRef.collection("transactions")
        
        // 1. Filter first (optimization suggestion)
        if let type = type {
            query = query.whereField("type", isEqualTo: type.rawValue)
        }
        
        // 2. Then Sort & Limit
        query = query.order(by: "date", descending: true)
            .limit(to: limit)

        
        if let lastDoc = lastDoc {
            query = query.start(afterDocument: lastDoc)
        }
        
        let snapshot = try await query.getDocuments()
        let transactions = snapshot.documents.compactMap { try? $0.data(as: Transaction.self) }
        return (transactions, snapshot.documents.last)
    }
    
    // Simple statistics fetch (Client-side calculation for now as aggregation queries might be complex/costly without specific design)
    // For a real production app with massive data, use Firestore Aggregation Queries or Cloud Functions.
    func fetchTransactionStats(walletId: String, from date: Date) async throws -> (income: Double, expense: Double) {
        let walletRef = db.collection("wallets").document(walletId)
        let snapshot = try await walletRef.collection("transactions")
            .whereField("date", isGreaterThanOrEqualTo: date)
            .getDocuments()
        
        var income: Double = 0
        var expense: Double = 0
        
        for doc in snapshot.documents {
            guard let transaction = try? doc.data(as: Transaction.self) else { continue }
            if transaction.type == .income {
                income += transaction.amount
            } else {
                expense += transaction.amount
            }
        }
        
        return (income, expense)
    }
    
    // Calcluate Savings Balance by fetching all relevant transactions and filtering client-side
    // This aligns with the optimistic logic and supports "Contains" matching.
    // Enhanced signature to return debug info if needed (tuple)
    func fetchSavingsBalance(walletId: String) async throws -> (balance: Double, debugInfo: String) {
        let walletRef = db.collection("wallets").document(walletId)
        
        // Fetch all transactions (optimized by ordering if needed, but for MVP just get all)
        let snapshot = try await walletRef.collection("transactions").getDocuments()
        
        var balance: Double = 0
        var processedCount = 0
        var matchCount = 0
        var errorCount = 0
        
        var expCount = 0
        var incCount = 0
        var rawSum: Double = 0
        
        for doc in snapshot.documents {
            do {
                let transaction = try doc.data(as: Transaction.self)
                processedCount += 1
                
                // Logic:
                // + Expense to "Birikim" or "Yatırım" (Money into Savings)
                // - Income ONLY from "Birikim Bozdurma" (Money withdrawn from Savings)
                // We must NOT subtract generic Investment Income (Dividends/Profit) as that creates a massive deficit.
                
                if transaction.type == .expense {
                    // Check Main Category for "Birikim" or "Yatırım"
                    if transaction.categoryName.localizedCaseInsensitiveContains("Birikim") || 
                       transaction.categoryName.localizedCaseInsensitiveContains("Yatırım") {
                        matchCount += 1
                        balance += transaction.amount
                        rawSum += transaction.amount
                        expCount += 1
                    }
                } else if transaction.type == .income {
                    // Check Sub Category for "Birikim" or "Bozdurma" specifically
                    // Or if user named a main category "Birikim Geliri" etc.
                    if transaction.subCategoryName.localizedCaseInsensitiveContains("Birikim") || 
                       transaction.subCategoryName.localizedCaseInsensitiveContains("Bozdurma") {
                        matchCount += 1
                        balance -= transaction.amount
                        rawSum -= transaction.amount
                        incCount += 1
                    }
                }
            } catch {
                errorCount += 1
                // print("Decoding error for doc \(doc.documentID): \(error)")
            }
        }
        
        return (max(0, balance), "M:\(matchCount) | E:\(expCount) I:\(incCount) | Sum:\(Int(rawSum)) | Err:\(errorCount)")
    }
    
    // MARK: - Debt Operations
    
    func addDebt(walletId: String, debt: Debt) async throws -> String {
        let walletRef = db.collection("wallets").document(walletId)
        let debtsRef = walletRef.collection("debts")
        
        let docRef = try debtsRef.addDocument(from: debt)
        return docRef.documentID
    }
    
    func fetchActiveDebts(walletId: String) async throws -> [Debt] {
        let walletRef = db.collection("wallets").document(walletId)
        let snapshot = try await walletRef.collection("debts")
            .whereField("status", isEqualTo: DebtStatus.active.rawValue)
            .getDocuments()
            
        return snapshot.documents.compactMap { try? $0.data(as: Debt.self) }
    }
    
    func updateDebt(walletId: String, debt: Debt) async throws {
        guard let debtId = debt.id else { return }
        let walletRef = db.collection("wallets").document(walletId)
        try walletRef.collection("debts").document(debtId).setData(from: debt, merge: true)
    }
    
    func deleteDebt(walletId: String, debtId: String) async throws {
        let walletRef = db.collection("wallets").document(walletId)
        try await walletRef.collection("debts").document(debtId).delete()
    }
    
    /// Reverts a debt installment payment (called when an installment transaction is deleted)
    func rollbackDebtInstallment(walletId: String, debtId: String, amount: Double) async throws {
        let walletRef = db.collection("wallets").document(walletId)
        let debtRef = walletRef.collection("debts").document(debtId)
        
        // Use a transaction to ensure atomic update if possible, but for MVP simple update is okay.
        // We will just read-modify-write here since we don't have a transaction infrastructure set up in this Service class easily.
        // Actually Firestore.firestore().runTransaction is robust. Let's use getDocument and update.
        
        let doc = try await debtRef.getDocument()
        guard var debt = try? doc.data(as: Debt.self) else { return }
        
        // Revert counters
        debt.paidInstallments -= 1
        if debt.paidInstallments < 0 { debt.paidInstallments = 0 }
        
        debt.remainingAmount += amount
        // Limit remaining amount to total? No, maybe amount changed, but logic should hold.
        // Just ensure it doesn't exceed totalAmount theoretically, but simpler to just add back.
        if debt.remainingAmount > debt.totalAmount {
             // Optional safety: debt.remainingAmount = debt.totalAmount
        }
        
        // If it was completed, make it active again
        if debt.status == .completed {
            debt.status = .active
        }
        
        // Note: We do NOT rollback nextDueDate because we don't know the exact schedule easily 
        // without complex recalculation. 
        // However, if the user deleted the *latest* installment, technically the date should revert.
        // But if they deleted a past one, date shouldn't change.
        // For now, we only trust the counters.
        
        try debtRef.setData(from: debt, merge: true)
    }
    
    // Fetch all debts (active and completed)
    func fetchAllDebts(walletId: String) async throws -> [Debt] {
        let walletRef = db.collection("wallets").document(walletId)
        let snapshot = try await walletRef.collection("debts")
            .order(by: "nextDueDate", descending: false)
            .getDocuments()
            
        return snapshot.documents.compactMap { try? $0.data(as: Debt.self) }
    }
    
    // Fetch ALL transactions for export/analytics (Be careful with cost)
    func fetchAllTransactions(walletId: String) async throws -> [Transaction] {
        let walletRef = db.collection("wallets").document(walletId)
        let snapshot = try await walletRef.collection("transactions")
            .order(by: "date", descending: true)
            .getDocuments()
        
        return snapshot.documents.compactMap { try? $0.data(as: Transaction.self) }
    }
    
    // MARK: - User & Member Management
    
    func findUser(byUsername username: String) async throws -> User? {
        let snapshot = try await db.collection("users")
            .whereField("username", isEqualTo: username)
            .limit(to: 1)
            .getDocuments()
        
        return try snapshot.documents.first?.data(as: User.self)
    }
    
    func fetchUsers(uids: [String]) async throws -> [User] {
        guard !uids.isEmpty else { return [] }
        // Firestore 'in' query supports up to 30 items. 
        // We will slice if needed or assume <30 for this MVP.
        let chunks = stride(from: 0, to: uids.count, by: 10).map {
            Array(uids[$0..<min($0 + 10, uids.count)])
        }
        
        var users: [User] = []
        for chunk in chunks {
            let snapshot = try await db.collection("users")
                .whereField("uid", in: chunk)
                .getDocuments()
            let chunkUsers = snapshot.documents.compactMap { try? $0.data(as: User.self) }
            users.append(contentsOf: chunkUsers)
        }
        return users
    }
    
    func addMember(walletId: String, userId: String, role: String) async throws {
        let walletRef = db.collection("wallets").document(walletId)
        
        // Atomically add to members array and update permissions map
        try await walletRef.updateData([
            "members": FieldValue.arrayUnion([userId]),
            "permissions.\(userId)": role
        ])
    }
    
    func removeMember(walletId: String, userId: String) async throws {
        let walletRef = db.collection("wallets").document(walletId)
        
        // Remove from members array and delete from permissions map
        try await walletRef.updateData([
            "members": FieldValue.arrayRemove([userId]),
            "permissions.\(userId)": FieldValue.delete()
        ])
    }
    

    func updateMemberRole(walletId: String, userId: String, newRole: String) async throws {
        let walletRef = db.collection("wallets").document(walletId)
        try await walletRef.updateData([
            "permissions.\(userId)": newRole
        ])
    }
    
    // MARK: - Invitations
    
    func sendInvite(walletId: String, walletName: String, toUser: User, fromUser: User, role: String) async throws {
        // Create invite document
        let inviteData = Invite(
            fromUserId: fromUser.uid,
            fromUsername: fromUser.username,
            toUserId: toUser.uid,
            toUsername: toUser.username,
            walletId: walletId,
            walletName: walletName,
            role: role,
            status: .pending,
            createdAt: Date()
        )
        
        try db.collection("invites").addDocument(from: inviteData)
        
        // Pre-add member as "pending" so they can update themselves later
        // "pending" role should block them from viewing details if we enforce it in Rules,
        // or just block editing in UI.
        try await addMember(walletId: walletId, userId: toUser.uid, role: "pending")
    }
    
    func fetchPendingInvites(forUser userId: String) async throws -> [Invite] {
        let snapshot = try await db.collection("invites")
            .whereField("toUserId", isEqualTo: userId)
            .whereField("status", isEqualTo: "pending")
            .getDocuments()
        
        return snapshot.documents.compactMap { try? $0.data(as: Invite.self) }
    }
    
    func respondToInvite(_ invite: Invite, accept: Bool) async throws {
        guard let inviteId = invite.id else { return }
        let inviteRef = db.collection("invites").document(inviteId)
        
        if accept {
            // 1. Update invite status
            try await inviteRef.updateData(["status": InviteStatus.accepted.rawValue])
            
            // 2. Upgrade member role from "pending" to "editor" (or whatever invite role was)
            // Note: User is already in 'members' array from sendInvite step.
            try await updateMemberRole(walletId: invite.walletId, userId: invite.toUserId, newRole: "editor")
            
            // 3. Fetch the now-accessible wallet and add to local list (Optimistic-ish)
            // Since rules now allow reading, this fetch should succeed.
            if let acceptedWallet = try? await getWallet(id: invite.walletId) {
                DispatchQueue.main.async {
                    if !self.wallets.contains(where: { $0.id == acceptedWallet.id }) {
                        self.wallets.append(acceptedWallet)
                    }
                }
            }
        } else {
            // Update status to rejected
            try await inviteRef.updateData(["status": InviteStatus.rejected.rawValue])
            
            // If rejected, REMOVE them from pending members
            try await removeMember(walletId: invite.walletId, userId: invite.toUserId)
            
            // Send notification to the inviter
            // We need to fetch the invite details (which we have) to know who sent it
            try? await sendNotification(
                toUserId: invite.fromUserId,
                title: "Davet Reddedildi",
                message: "\(invite.toUsername) cüzdan davetinizi reddetti.",
                type: .rejection,
                relatedId: invite.walletId
            )
        }
    }
    
    // MARK: - Permission Requests
    
    func sendPermissionRequest(wallet: Wallet, fromUser: User) async throws {
        guard let walletId = wallet.id else { return }
        
        // Create request
        let request = PermissionRequest(
            fromUserId: fromUser.uid,
            fromUsername: fromUser.username,
            toOwnerId: wallet.ownerId,
            walletId: walletId,
            walletName: wallet.name,
            status: .pending,
            createdAt: Date()
        )
        
        try db.collection("permission_requests").addDocument(from: request)
    }
    
    func fetchPermissionRequests(forOwner ownerId: String) async throws -> [PermissionRequest] {
        print("DEBUG: Fetching requests for owner: \(ownerId)")
        let snapshot = try await db.collection("permission_requests")
            .whereField("toOwnerId", isEqualTo: ownerId)
            .whereField("status", isEqualTo: "pending")
            .getDocuments()
            
        print("DEBUG: Found \(snapshot.documents.count) requests")
        return snapshot.documents.compactMap { try? $0.data(as: PermissionRequest.self) }
    }
    
    func respondToPermissionRequest(_ request: PermissionRequest, accept: Bool) async throws {
        guard let requestId = request.id else { return }
        let requestRef = db.collection("permission_requests").document(requestId)
        
        if accept {
            try await requestRef.updateData(["status": PermissionRequestStatus.accepted.rawValue])
            // Update role to editor
            try await updateMemberRole(walletId: request.walletId, userId: request.fromUserId, newRole: "editor")
        } else {
            try await requestRef.updateData(["status": PermissionRequestStatus.rejected.rawValue])
        }
    }
    // MARK: - Notifications (Generic)
    
    func sendNotification(toUserId: String, title: String, message: String, type: NotificationType, relatedId: String? = nil) async throws {
        let notification = AppNotification(
            userId: toUserId,
            title: title,
            message: message,
            type: type,
            relatedId: relatedId,
            isRead: false,
            createdAt: Date()
        )
        try db.collection("notifications").addDocument(from: notification)
    }
    
    func fetchNotifications(forUser userId: String) async throws -> [AppNotification] {
        let snapshot = try await db.collection("notifications")
            .whereField("userId", isEqualTo: userId)
            .order(by: "createdAt", descending: true)
            .limit(to: 20)
            .getDocuments()
            
        return snapshot.documents.compactMap { try? $0.data(as: AppNotification.self) }
    }
    
    func markNotificationRead(_ notificationId: String) async throws {
        try await db.collection("notifications").document(notificationId).updateData(["isRead": true])
    }
    
    // MARK: - Data Repair (Temporary)
    func repairTransactions() async throws -> String {
        var log = "Onarım Başlatıldı...\n"
        var updatedCount = 0
        
        // 1. Get all wallets
        let walletsSnap = try await db.collection("wallets").getDocuments()
        log += "Bulunan Cüzdan Sayısı: \(walletsSnap.documents.count)\n"
        
        for walletDoc in walletsSnap.documents {
            let walletId = walletDoc.documentID
            let walletRef = db.collection("wallets").document(walletId)
            let transactionsSnap = try await walletRef.collection("transactions").getDocuments()
            
            for doc in transactionsSnap.documents {
                var updates: [String: Any] = [:]
                let data = doc.data()
                
                // Fix Type (Lowercase)
                if let typeString = data["type"] as? String {
                    let lowered = typeString.lowercased()
                    if typeString != lowered {
                        updates["type"] = lowered
                        log += "Düzeltildi (Type): \(doc.documentID) -> \(lowered)\n"
                    }
                }
                
                // Backfill Username
                if data["createdByUsername"] == nil {
                    if let uid = data["createdBy"] as? String {
                        // Fetch user info (One by one is slow but acceptable for repair tool)
                        let userDoc = try await db.collection("users").document(uid).getDocument()
                        if let userData = userDoc.data(), let username = userData["username"] as? String {
                            updates["createdByUsername"] = username
                            log += "Eklendi (Username): \(doc.documentID) -> \(username)\n"
                        }
                    }
                }
                
                if !updates.isEmpty {
                    try await doc.reference.updateData(updates)
                    updatedCount += 1
                }
            }
        }
        
        log += "Tamamlandı. Toplam Güncellenen İşlem: \(updatedCount)"
        return log
    }
    // MARK: - Report Operations
    
    func saveReport(_ report: Report) async throws {
        let walletRef = db.collection("wallets").document(report.walletId)
        let reportsRef = walletRef.collection("reports")
        
        try reportsRef.addDocument(from: report)
    }
    
    func fetchReports(walletId: String) async throws -> [Report] {
        let walletRef = db.collection("wallets").document(walletId)
        let snapshot = try await walletRef.collection("reports")
            .order(by: "createdAt", descending: true)
            .getDocuments()
            
        return snapshot.documents.compactMap { try? $0.data(as: Report.self) }
    }
    
    // Advanced Transaction Fetch (Filtering)
    func fetchTransactions(walletId: String, startDate: Date, endDate: Date, memberId: String? = nil) async throws -> [Transaction] {
        let walletRef = db.collection("wallets").document(walletId)
        var query = walletRef.collection("transactions")
            .whereField("date", isGreaterThanOrEqualTo: startDate)
            .whereField("date", isLessThanOrEqualTo: endDate)
            // .order(by: "date", descending: true) // Requires composite index if combined with other filters
        
        if let memberId = memberId {
            query = query.whereField("createdBy", isEqualTo: memberId)
        }
        
        let snapshot = try await query.getDocuments()
        let transactions = snapshot.documents.compactMap { try? $0.data(as: Transaction.self) }
        
        // Manual sort to avoid needing complex composite indexes for every combination in MVP
        return transactions.sorted(by: { $0.date > $1.date })
    }
}
